IF EXISTS
   (
      SELECT *
      FROM sys.databases d
      WHERE d.name = N'PrimaryData'
   )
BEGIN
   DECLARE @Msg varchar(256) = 'Database PrimaryData already exists.';
   PRINT @Msg;
   RETURN;
END;

CREATE DATABASE PrimaryData
COLLATE SQL_Latin1_General_CP1_CI_AS;

ALTER DATABASE PrimaryData
SET
   ANSI_NULLS ON,
   ANSI_PADDING ON,
   ANSI_WARNINGS ON,
   ARITHABORT ON,
   AUTO_CLOSE OFF,
   AUTO_CREATE_STATISTICS ON,
   AUTO_SHRINK OFF,
   AUTO_UPDATE_STATISTICS ON,
   CONCAT_NULL_YIELDS_NULL ON,
   NUMERIC_ROUNDABORT OFF,
   QUOTED_IDENTIFIER OFF,
   RECURSIVE_TRIGGERS OFF,
   ALLOW_SNAPSHOT_ISOLATION ON,
   RECOVERY SIMPLE;
GO