DROP TABLE IF EXISTS Season.Team;
DROP TABLE IF EXISTS Season.Player;
DROP TABLE IF EXISTS Season.TeamType;
DROP TABLE IF EXISTS Season.Game;
DROP TABLE IF EXISTS Season.TeamGame;
DROP TABLE IF EXISTS Season.PlayerGame;